### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [sunwj/SunVolumeRender#1]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/118404067-fb7b0500-b6a3-11eb-9252-4c5a93ca10f4.png)

thank you  
best regards to you  
William

**Comment by sunwj** [comment]
It says that your VTK is not installed or configured properly.
